### PR TITLE
PBP-490: order list view

### PR DESCRIPTION
**Pull request by nariodh**
## Jira:

[PBP-490](https://jira.deliveryhero.com/browse/PBP-490)

## Description

Added Order List view

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring change (no changes in functionality, e.g: cleaning up code)
- [ ] This change requires a documentation update

## Screenshot
Screenshot 2023-03-23 at 23 13 37

Screenshot 2023-03-24 at 10 21 54

### CODE REVIEW

**Review by tejazz — CHANGES_REQUESTED** [review]
I see a lot of things missing/incorrectly implemented.

1. The order structure is incorrect. This is the order record structure returned from the API. (The BFF layer mapping will be determined in the task currently in progress) 
```
  {
            "order_code": "xjka-17s8",
            "flow": "LATEST",
            "order_placed_at": "2023-03-21",
            "status": "received",
            "vendor_code": "xjka",
            "is_billable": true,
            "is_skipped": false,
            "updated_at": "2023-03-17T18:02:42.378227928Z",
            "latest_event_type": "billable_flag_updated",  // omit
            "latest_event_timestamp": "2023-03-21T18:02:42.248Z",  // omit
            "TTL": 1679356800  // omit
  }
```
2. No infinite scroll for fetching further orders?
3. Selected filters `selected` chips implementation?
image

**Comment by nariodh** [comment]
oh yes, I forgot about the infinite scroll. that I will add shortly but concerning the rest, I think there was a misunderstanding - I thought we don't display the values that come from the filters we are not adding yet. I will fix this too. The chip implementation is tricky as armor allows changing the size to small only. Shall we just create our own implementation then or stick to armor component?

**Comment by tejazz** [comment]
> oh yes, I forgot about the infinite scroll. that I will add shortly but concerning the rest, I think there was a misunderstanding - I thought we don't display the values that come from the filters we are not adding yet. I will fix this too. The chip implementation is tricky as armor allows changing the size to small only. Shall we just create our own implementation then or stick to armor component?

I would say. Let's sync on the changes tomorrow morning before you proceed. It would be easier to align and we will update the description as well to make sure that the communication is recorded. What do you think?

**Comment by nariodh** [comment]
@tejazz also added the selected filters screenshot.

**Comment by tejazz** [comment]
Marking this PR as closed since a major portion of this PR was integrated into this one. #12

**Pull request closed without merging**
